USE ODS;

-- ODS_DM_CICLO_FACTURACION
INSERT INTO ODS_DM_CICLO_FACTURACION (DE_CICLO_FACTURACION, FC_INSERT, FC_MODIF)
	SELECT DISTINCT(UPPER(TRIM(BILL_CYCLE))) AS BILL_CYCLE, NOW(), NOW() FROM STAGE.STG_FACTURAS_FCT
    WHERE BILL_CYCLE<>'';

INSERT INTO ODS_DM_CICLO_FACTURACION VALUES (999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_CICLO_FACTURACION VALUES (998, 'NO APLICA', NOW(), NOW());

COMMIT;
ANALYZE TABLE ODS_DM_CICLO_FACTURACION;


-- ODS_DM_METODO_PAGO
INSERT INTO ODS_DM_METODO_PAGO (DE_METODO_PAGO, FC_INSERT, FC_MODIF)
	SELECT DISTINCT(UPPER(TRIM(BILL_METHOD))) AS BILL_METHOD, NOW(), NOW() FROM STAGE.STG_FACTURAS_FCT
    WHERE BILL_METHOD<>'';

INSERT INTO ODS_DM_METODO_PAGO VALUES (999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_METODO_PAGO VALUES (998, 'NO APLICA', NOW(), NOW());

COMMIT;
ANALYZE TABLE ODS_DM_METODO_PAGO;

-- ODS_HC_FACTURAS
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO ODS_HC_FACTURAS
	SELECT TRIM(BILL_REF_NO) AS ID_FACTURA,
    TRIM(CUSTOMER_ID) AS ID_CLIENTE,
    CASE WHEN TRIM(SFF.START_DATE)<>'' THEN STR_TO_DATE(SFF.START_DATE, '%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END AS FC_COMIENZO,
    CASE WHEN TRIM(SFF.END_DATE)<>'' THEN STR_TO_DATE(SFF.END_DATE, '%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END AS FC_FIN,
    CASE WHEN TRIM(SFF.STATEMENT_DATE)<>'' THEN STR_TO_DATE(SFF.STATEMENT_DATE, '%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END AS FC_FC_ESTABLECIMIENTO,
    CASE WHEN TRIM(SFF.PAYMENT_DATE)<>'' THEN STR_TO_DATE(SFF.PAYMENT_DATE, '%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END AS FC_PAGO,
    ODCF.ID_CICLO_FACTURACION AS ID_CICLO_FACTURACION,
    AMOUNT AS IMPORTE,
    ODMP.ID_METODO_PAGO AS ID_METODO_PAGO,
    NOW(),
    NOW()
    FROM STAGE.STG_FACTURAS_FCT SFF
    INNER JOIN ODS.ODS_DM_CICLO_FACTURACION ODCF ON CASE WHEN TRIM(SFF.BILL_CYCLE)<>'' THEN UPPER(TRIM(SFF.BILL_CYCLE)) ELSE 'DESCONOCIDO' END=ODCF.DE_CICLO_FACTURACION
    INNER JOIN ODS.ODS_DM_METODO_PAGO ODMP ON CASE WHEN TRIM(SFF.BILL_METHOD)<>'' THEN UPPER(TRIM(SFF.BILL_METHOD)) ELSE 'DESCONOCIDO' END=ODMP.DE_METODO_PAGO;
    
SET FOREIGN_KEY_CHECKS=1;

COMMIT;
ANALYZE TABLE ODS_HC_FACTURAS;

