USE ODS;

-- ODS_DM_AGENTES
INSERT INTO ODS_DM_AGENTES (DE_AGENTE, FC_INSERT, FC_MODIF)
	SELECT DISTINCT(UPPER(TRIM(SCI.AGENT))),
    NOW(),
    NOW()
	FROM STAGE.STG_CONTACTOS_IVR SCI
	WHERE SCI.AGENT<>'';

INSERT INTO ODS_DM_AGENTES VALUES (999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_AGENTES VALUES (998, 'NO APLICA', NOW(), NOW());

COMMIT;
ANALYZE TABLE ODS_DM_AGENTES;


-- ODS_DM_SERVICIOS
INSERT INTO ODS_DM_SERVICIOS (DE_SERVICIO, FC_INSERT, FC_MODIF)
	SELECT DISTINCT(UPPER(TRIM(SCI.SERVICE))),
    NOW(),
    NOW()
	FROM STAGE.STG_CONTACTOS_IVR SCI
	WHERE SCI.SERVICE<>'';

INSERT INTO ODS_DM_SERVICIOS VALUES (999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_SERVICIOS VALUES (998, 'NO APLICA', NOW(), NOW());

COMMIT;
ANALYZE TABLE ODS_DM_SERVICIOS;


-- ODS_HC_LLAMADAS
INSERT INTO ODS_HC_LLAMADAS (STG_ID_CONTACTO, TELEFONO, FC_COMIENZO, FC_FIN, ID_SERVICIO, TRANSFERIDO, ID_AGENTE, FC_INSERT, FC_MODIF)
	SELECT ID,
	CASE WHEN TRIM(SCI.PHONE_NUMBER)<>'' THEN TRIM(SCI.PHONE_NUMBER) ELSE 9999999999 END,
    CASE WHEN TRIM(SCI.START_DATETIME)<>'' THEN STR_TO_DATE(TRIM(SCI.START_DATETIME), '%Y-%m-%d %H:%i:%s.%f') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END,
	CASE WHEN TRIM(SCI.END_DATETIME)<>'' THEN STR_TO_DATE(TRIM(SCI.END_DATETIME), '%Y-%m-%d %H:%i:%s.%f') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END,
	ODS.ID_SERVICIO,
	CASE WHEN UPPER(TRIM(FLG_TRANSFER))='TRUE' THEN TRUE ELSE FALSE END,
	ODA.ID_AGENTE,
    NOW(),
    NOW()
	FROM STAGE.STG_CONTACTOS_IVR SCI
    INNER JOIN ODS_DM_AGENTES ODA ON CASE WHEN TRIM(SCI.AGENT)<>'' THEN UPPER(TRIM(SCI.AGENT)) ELSE 'DESCONOCIDO' END = ODA.DE_AGENTE
    INNER JOIN ODS_DM_SERVICIOS ODS ON CASE WHEN TRIM(SCI.SERVICE)<>'' THEN UPPER(TRIM(SCI.SERVICE)) ELSE 'DESCONOCIDO' END = ODS.DE_SERVICIO;

COMMIT;
ANALYZE TABLE ODS_HC_LLAMADAS;
