USE ODS;

-- ESTUDIO NOMBRE VIAS
SELECT COUNT(SUBSTR(OHD.DE_DIRECCION, LOCATE(' ', OHD.DE_DIRECCION) + 1)),
	COUNT(DISTINCT(SUBSTR(OHD.DE_DIRECCION, LOCATE(' ', OHD.DE_DIRECCION) + 1)))
	FROM ODS.ODS_HC_DIRECCIONES OHD
    WHERE SUBSTR(OHD.DE_DIRECCION, LOCATE(' ', OHD.DE_DIRECCION) + 1)<>'';

-- CREACIÓN TABLA ODS_DM_NOMBRE_VIA
DROP TABLE IF EXISTS ODS_DM_NOMBRE_VIA;
CREATE TABLE ODS_DM_NOMBRE_VIA (
	ID_NOMBRE_VIA INT(11) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	DE_NOMBRE_VIA VARCHAR(512),
    FC_INSERT DATETIME,
    FC_MODIF DATETIME
);

-- INSERCIÓN ODS_DM_NOMBRE_VIA
INSERT INTO ODS_DM_NOMBRE_VIA (DE_NOMBRE_VIA, FC_INSERT, FC_MODIF)
SELECT DISTINCT(SUBSTR(OHD.DE_DIRECCION, LOCATE(' ', OHD.DE_DIRECCION) + 1)),
	NOW(),
    NOW()
	FROM ODS.ODS_HC_DIRECCIONES OHD
    WHERE OHD.DE_DIRECCION<>'NO APLICA' AND OHD.DE_DIRECCION<>'DESCONOCIDO' AND SUBSTR(OHD.DE_DIRECCION, LOCATE(' ', OHD.DE_DIRECCION) + 1)<>'';

INSERT INTO ODS_DM_NOMBRE_VIA VALUES (999999999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_NOMBRE_VIA VALUES (999999998, 'NO APLICA', NOW(), NOW());

COMMIT;
ANALYZE TABLE ODS_DM_NOMBRE_VIA;

-- CREACIÓN DE LAS COLUMNAS EN ODS_HC_DIRECCIONES
ALTER TABLE ODS.ODS_HC_DIRECCIONES
ADD COLUMN NUM_VIA INT(11) UNSIGNED NOT NULL AFTER DE_DIRECCION;
ALTER TABLE ODS.ODS_HC_DIRECCIONES
ADD COLUMN ID_NOMBRE_VIA INT(11) UNSIGNED NOT NULL AFTER NUM_VIA;


-- ES NECESARIO QUITAR LA OPCIÓN DE SAFE UPDATES/DELETES Y RECONECTAR CON EL DBMS

-- ACTUALIZACION DEL CAMPO ID_NOMBRE_VIA
UPDATE ODS_HC_DIRECCIONES OHD
INNER JOIN ODS_DM_NOMBRE_VIA ODNV ON 
	SUBSTR(OHD.DE_DIRECCION, LOCATE(' ', OHD.DE_DIRECCION) + 1) = ODNV.DE_NOMBRE_VIA
	SET OHD.ID_NOMBRE_VIA = ODNV.ID_NOMBRE_VIA, FC_MODIF = NOW()
	WHERE OHD.DE_DIRECCION <> 'DESCONOCIDO' AND OHD.DE_DIRECCION <> 'NO APLICA';


UPDATE ODS_HC_DIRECCIONES OHD
	SET OHD.ID_NOMBRE_VIA = 999999999, OHD.FC_MODIFICACION = NOW()
	WHERE OHD.DE_DIRECCION='DESCONOCIDO';

UPDATE ODS_HC_DIRECCIONES OHD
	SET OHD.ID_NOMBRE_VIA = 999999998, OHD.FC_MODIFICACION = NOW()
	WHERE OHD.DE_DIRECCION='NO APLICA';


-- ACTUALIZACION DEL CAMPO NUM_VIA
UPDATE ODS_HC_DIRECCIONES OHD
	SET OHD.NUM_VIA = CAST(SUBSTRING_INDEX(OHD.DE_DIRECCION, ' ', 1) AS UNSIGNED), OHD.FC_MODIFICACION = NOW()
	WHERE OHD.DE_DIRECCION<>'DESCONOCIDO' AND OHD.DE_DIRECCION<>'NO APLICA';


UPDATE ODS_HC_DIRECCIONES OHD
	SET OHD.NUM_VIA = 999999999, OHD.FC_MODIFICACION = NOW()
	WHERE OHD.DE_DIRECCION='DESCONOCIDO';

UPDATE ODS_HC_DIRECCIONES OHD
	SET OHD.NUM_VIA = 999999998, OHD.FC_MODIFICACION = NOW()
	WHERE OHD.DE_DIRECCION='NO APLICA';


-- ESTABLECIMIENTO FK CON TABLA ODS_DM_NOMBRE_VIA
ALTER TABLE ODS_HC_DIRECCIONES ADD INDEX fk_dir_nom_v_idx (ID_NOMBRE_VIA ASC);
ALTER TABLE ODS_HC_DIRECCIONES ADD CONSTRAINT fk_dir_nom_v FOREIGN KEY (ID_NOMBRE_VIA)
     REFERENCES ODS_DM_NOMBRE_VIA(ID_NOMBRE_VIA);

-- BORRADO DE LA COLUMNA DE_DIRECCION
ALTER TABLE ODS_HC_DIRECCIONES
DROP COLUMN DE_DIRECCION;

